import { describe,expect,it } from 'vitest';import { detectType,isIdentifierOnlyDataset,profileRows } from '../analytics/typeDetection';import { duplicateCount,summarize } from '../analytics/dataSummary';import { aggregate,median,topN } from '../analytics/aggregations';import { applyFilters } from '../analytics/filters';import { suggestCharts } from '../analytics/chartSuggestions';import { insights } from '../analytics/insights';import { bankSample } from '../data/samples';import { toCsv } from '../utils/csvExport';
import { preferredNumericTarget } from '../analytics/chartSuggestions';
import { chartBuilderError } from '../analytics/chartValidation';
describe('type detection',()=>{it('detects numeric, date, categorical, binary, and identifiers conservatively',()=>{expect(detectType([1,2,3],'age')).toBe('numeric');expect(detectType(['2025-01-01','2025-02-02'],'date')).toBe('date');expect(detectType(['red','blue','red'],'color')).toBe('categorical');expect(detectType(['yes','no','yes'],'y')).toBe('binary');expect(detectType(Array.from({length:30},(_,i)=>`C-${i}`),'customer_id')).toBe('identifier')})});
it('detects numeric identifiers with spaced names without matching valid id substrings',()=>{const values=Array.from({length:30},(_,i)=>100001+i);expect(detectType(values,'Customer ID')).toBe('identifier');expect(detectType(values,'Order ID')).toBe('identifier');expect(detectType(values,'Account Number')).toBe('identifier');expect(detectType(values,'Paid Revenue')).toBe('numeric');expect(detectType(values,'Dividend')).toBe('numeric')});
it('does not interpret hyphenated or repeated business identifiers as dates',()=>{const ids=Array.from({length:30},(_,i)=>`ORD-${1001+i}`),customers=Array.from({length:30},(_,i)=>`CUS-${200+i%5}`);expect(detectType(ids,'order_id')).toBe('identifier');expect(detectType(customers,'customer_id')).toBe('identifier');expect(detectType(['2025-01-01','2025-02-02'],'order_date')).toBe('date')});
describe('summary and math',()=>{const rows=[{a:1,g:'x',y:'yes'},{a:3,g:'x',y:'no'},{a:null,g:'z',y:'yes'},{a:null,g:'z',y:'yes'}];it('counts missing and duplicates',()=>{const p=profileRows(rows);expect(summarize(rows,p).missing).toBe(2);expect(duplicateCount(rows)).toBe(1)});it('computes median and aggregations',()=>{expect(median([9,1,3,5])).toBe(4);expect(aggregate(rows,'g','a','average')[0].value).toBe(2);expect(aggregate(rows,'g',undefined,'outcomeRate','y')[0].value).toBe(50)});it('groups top N',()=>{expect(topN([{name:'a',value:3},{name:'b',value:2},{name:'c',value:1}],2)).toEqual([{name:'a',value:3},{name:'b',value:2},{name:'Other',value:1,count:0}])});it('filters rows',()=>{expect(applyFilters(rows,{g:{kind:'category',values:['z']}})).toHaveLength(2);expect(applyFilters(rows,{a:{kind:'numeric',min:2,max:5}})).toHaveLength(1)})});
it('excludes missing numeric values from aggregations and observations',()=>{const rows=[{group:'A',value:null},{group:'A',value:''},{group:'B',value:4},{group:'B',value:8}],profiles=profileRows(rows);expect(aggregate(rows,'group','value','average')).toEqual([{name:'B',value:6,count:2}]);const text=insights(rows,profiles).join(' ');expect(text).toContain('median value was 6');expect(text).toContain('average of 6');expect(text).not.toContain('average of 3')});
it('returns an explicit observation state for an empty filtered population',()=>expect(insights([],profileRows([{value:4}]))).toEqual(['No observations are available for the current filters.']));
describe('Bank Marketing regression',()=>{const p=profileRows(bankSample);const type=(n:string)=>p.find(x=>x.name===n)?.type;it('keeps field semantics conservative',()=>{expect(type('y')).toBe('binary');expect(type('campaign')).toBe('numeric');expect(type('age')).toBe('numeric');expect(type('job')).toBe('categorical');expect(type('education')).toBe('categorical');expect(type('job')).not.toBe('date')});it('suggests sensible charts with no funnel invention',()=>{const charts=suggestCharts(p);const titles=charts.map(x=>x.title.toLowerCase()).join(' ');expect(charts[0].x).toBe('y');expect(titles).not.toContain('funnel');expect(titles).not.toContain('roas');expect(titles).not.toContain('conversion total')});it('creates evidence-supported observations and small group cautions',()=>{const text=insights(bankSample,p).join(' ');expect(text).toContain('positive y rate');expect(text).toMatch(/observed|median/);expect(text).not.toMatch(/caused|guaranteed/)})});
it('exports valid CSV',()=>expect(toCsv([{name:'A',value:2}])).toContain('name,value'));
describe('Advertising.csv regression',()=>{const rows=Array.from({length:200},(_,i)=>{const TV=(i*17)%300,radio=(i*7)%50,newspaper=(i*13)%100;return{'Unnamed: 0':i,TV,radio,newspaper,sales:Number((3+TV*.04+radio*.2+newspaper*.01).toFixed(2))}});const profiles=profileRows(rows);const charts=suggestCharts(profiles);it('detects the sequential unnamed column as an identifier',()=>expect(profiles.find(p=>p.name==='Unnamed: 0')?.type).toBe('identifier'));it('selects sales as the target and generates useful charts across all predictors',()=>{expect(preferredNumericTarget(profiles)?.name).toBe('sales');expect(charts.length).toBeGreaterThanOrEqual(4);expect(charts.every(chart=>chart.x!=='Unnamed: 0'&&chart.y!=='Unnamed: 0')).toBe(true);expect(charts.some(chart=>chart.title==='Sales distribution'&&chart.x==='sales')).toBe(true);expect(charts.some(chart=>chart.title==='TV vs sales'&&chart.x==='TV'&&chart.y==='sales')).toBe(true);expect(charts.some(chart=>chart.title==='Radio vs sales'&&chart.x==='radio'&&chart.y==='sales')).toBe(true);expect(charts.some(chart=>chart.title==='Newspaper vs sales'&&chart.x==='newspaper'&&chart.y==='sales')).toBe(true)});it('focuses observations on the target and strongest relationship',()=>{const text=insights(rows,profiles).join(' ');expect(text).toContain('median sales');expect(text).toContain('association with sales');expect(text).not.toContain('median TV')});it('enforces semantic builder combinations',()=>{const tv=profiles.find(p=>p.name==='TV')!,sales=profiles.find(p=>p.name==='sales')!;expect(chartBuilderError('scatter',tv,tv)).toContain('different');expect(chartBuilderError('horizontal',tv,undefined)).toContain('categorical');expect(chartBuilderError('scatter',tv,sales)).toBe('')})});
describe('identifier-only support state',()=>{const rows=(fields:Record<string,(i:number)=>unknown>)=>Array.from({length:30},(_,i)=>Object.fromEntries(Object.entries(fields).map(([name,value])=>[name,value(i)])));it.each([
 ['one string ID',rows({'Customer ID':i=>`C-${i}`})],['multiple string IDs',rows({'Customer ID':i=>`C-${i}`,'Order ID':i=>`O-${i}`})],['UUID',rows({'Transaction UUID':i=>`00000000-0000-4000-8000-${String(i).padStart(12,'0')}`})],['numeric customer ID',rows({'Customer ID':i=>100001+i})],['numeric order ID',rows({'Order ID':i=>90000021+i})],['numeric account number',rows({'Account Number':i=>45001234+i})],['date-like numeric ID',rows({'Order ID':i=>20250101+i})],['mixed identifier formats',rows({'Customer ID':i=>i%2?`C-${i}`:String(100000+i),'Transaction UUID':i=>`uuid-${i}`})]
 ])('recognizes %s datasets',(_,data)=>expect(isIdentifierOnlyDataset(profileRows(data))).toBe(true));it.each([
 ['Customer ID + Revenue',rows({'Customer ID':i=>`C-${i}`,Revenue:i=>i*10})],['Order ID + Profit',rows({'Order ID':i=>`O-${i}`,Profit:i=>i-5})],['Account ID + Status',rows({'Account ID':i=>`A-${i}`,Status:i=>i%2?'Open':'Closed'})],['Customer ID + Region',rows({'Customer ID':i=>`C-${i}`,Region:i=>['East','West'][i%2]})],['Customer ID + Date + Revenue',rows({'Customer ID':i=>`C-${i}`,Date:i=>`2025-01-${String(i%28+1).padStart(2,'0')}`,Revenue:i=>i*10})],['one numeric metric',rows({Revenue:i=>i*10})],['one category',rows({Region:i=>['East','West'][i%2]})]
 ])('keeps %s chartable',(_,data)=>expect(isIdentifierOnlyDataset(profileRows(data))).toBe(false));it.each(['Paid Revenue','Paid Orders','Bid Amount','Dividend','Midmarket Sales','Grid Revenue','Holiday Sales'])('does not classify %s from an id substring',name=>expect(detectType(Array.from({length:30},(_,i)=>i+1),name)).toBe('numeric'))});
