import { ChangeEvent,DragEvent,useMemo,useState } from 'react';
import ChartCard from './components/ChartCard';import { campaignSample,ecommerceSample,bankSample } from './data/samples';import { Dataset,FilterState,Row,ChartSpec,ColumnType,Aggregation } from './types';import { profileRows } from './analytics/typeDetection';import { summarize } from './analytics/dataSummary';import { suggestCharts } from './analytics/chartSuggestions';import { applyFilters } from './analytics/filters';import { insights } from './analytics/insights';import { parseFile } from './utils/fileParsing';import { downloadCsv } from './utils/csvExport';
import { builderUsesAggregation,builderUsesY,chartBuilderError,validBuilderX } from './analytics/chartValidation';
const fmt=(n:number)=>n.toLocaleString();
function makeDataset(name:string,rows:Row[]):Dataset{return{name,rows,originalRows:rows,profiles:profileRows(rows)}}
function PreviewTable({rows,columns}:{rows:Row[];columns:string[]}){return <div className="table-wrap"><table><thead><tr>{columns.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{rows.slice(0,20).map((r,i)=><tr key={i}>{columns.map(c=><td key={c}>{String(r[c]??'')}</td>)}</tr>)}</tbody></table></div>}
function Header({onReset}:{onReset?:()=>void}){return <header className="app-header"><button className="brand" onClick={onReset} aria-label="MarketLens home"><span>ML</span>MarketLens</button>{onReset&&<button className="ghost" onClick={onReset}>New dataset</button>}</header>}
function Upload({onLoad}:{onLoad:(d:Dataset)=>void}){const [error,setError]=useState('');const [loading,setLoading]=useState(false);const load=async(f?:File)=>{if(!f)return;setLoading(true);setError('');try{onLoad(makeDataset(f.name,await parseFile(f)))}catch(e){setError((e as Error).message)}finally{setLoading(false)}};const samples=[['Campaign Dataset',campaignSample],['Ecommerce Dataset',ecommerceSample],['Bank Marketing Dataset',bankSample]] as const;return <main className="start"><Header/><section className="hero"><div className="eyebrow">Explore data with confidence</div><h1>Turn your CSV into<br/><em>clear, beautiful insights.</em></h1><p>Upload a dataset and MarketLens will profile your columns, choose useful charts, and surface careful observations in seconds.</p></section><label className="drop" onDragOver={e=>e.preventDefault()} onDrop={(e:DragEvent)=>{e.preventDefault();load(e.dataTransfer.files[0])}}><input aria-label="Upload CSV or Excel" type="file" accept=".csv,.xlsx,.xls" onChange={(e:ChangeEvent<HTMLInputElement>)=>load(e.target.files?.[0])}/><div className="upload-icon">↥</div><strong>{loading?'Reading your data…':'Drop a CSV or Excel file here'}</strong><span>or click to browse · up to 10 MB</span></label>{error&&<div role="alert" className="error">{error}</div>}<div className="samples"><span>Or start with a sample</span><div>{samples.map(([name,rows])=><button key={name} onClick={()=>onLoad(makeDataset(name,rows))}>{name}<b>→</b></button>)}</div></div><p className="privacy">◉ Your data stays in this browser and is never uploaded.</p></main>}
function Summary({d,rows}:{d:Dataset;rows:Row[]}){const s=summarize(rows,d.profiles);return <section className="summary"><div><div className="eyebrow">Current dataset</div><h1>{d.name}</h1><p>{fmt(s.rows)} rows · {s.columns} columns · {s.missing} missing values · {s.duplicates} duplicate rows</p></div><div className="stats"><div><b>{s.numeric}</b><span>Numeric</span></div><div><b>{s.categorical}</b><span>Categorical</span></div><div><b>{s.date}</b><span>Date</span></div><div><b>{s.binary}</b><span>Binary</span></div></div></section>}
function Filters({d,value,onChange}:{d:Dataset;value:FilterState;onChange:(v:FilterState)=>void}){const suitable=d.profiles.filter(p=>(p.type==='categorical'||p.type==='binary')&&p.unique<=15).slice(0,3);return <section className="filterbar"><div><strong>Filter this view</strong><span>{Object.keys(value).length?`${Object.keys(value).length} active`:'All records'}</span></div>{suitable.map(p=><label key={p.name}>{p.name}<select value={(value[p.name] as any)?.values?.[0]||''} onChange={e=>{const next={...value};if(e.target.value)next[p.name]={kind:'category',values:[e.target.value]};else delete next[p.name];onChange(next)}}><option value="">All</option>{Array.from(new Set(p.values.map(String))).sort().map(v=><option key={v}>{v}</option>)}</select></label>)}<button className="ghost" onClick={()=>onChange({})} disabled={!Object.keys(value).length}>Reset filters</button></section>}
function Profile({d,setD}:{d:Dataset;setD:(d:Dataset)=>void}){return <details className="details-card"><summary><span><b>Column profile</b><small>Types, completeness, and examples</small></span><b>⌄</b></summary><div className="table-wrap"><table><thead><tr><th>Column</th><th>Detected type</th><th>Missing</th><th>Unique</th><th>Examples</th></tr></thead><tbody>{d.profiles.map(p=><tr key={p.name}><td><b>{p.name}</b></td><td><select aria-label={`Type for ${p.name}`} value={p.type} onChange={e=>setD({...d,profiles:d.profiles.map(x=>x.name===p.name?{...x,type:e.target.value as ColumnType}:x)})}>{['numeric','categorical','date','binary','identifier','text'].map(t=><option key={t}>{t}</option>)}</select></td><td>{p.missing}</td><td>{p.unique}</td><td>{p.examples.join(', ')}</td></tr>)}</tbody></table></div></details>}
type BuilderSelection={kind:ChartSpec['kind'];x:string;y:string;agg:Aggregation};
const numericAggregation=(name:string):Aggregation=>/(age|rate|ratio|percent|score|average|avg|price|balance)/i.test(name)?'average':'sum';
function builderDefaults(profiles:Dataset['profiles']):BuilderSelection{const date=profiles.find(p=>p.type==='date');const nums=profiles.filter(p=>p.type==='numeric');if(date&&nums[0])return{kind:'line',x:date.name,y:nums[0].name,agg:numericAggregation(nums[0].name)};if(nums.length>1)return{kind:'scatter',x:nums[0].name,y:nums[1].name,agg:'average'};if(nums[0])return{kind:'histogram',x:nums[0].name,y:'',agg:'count'};const donut=profiles.find(p=>['categorical','binary'].includes(p.type)&&p.unique<=15);if(donut)return{kind:'donut',x:donut.name,y:'',agg:'count'};const x=profiles.find(p=>p.type!=='text')?.name||profiles[0]?.name||'';return{kind:'bar',x,y:'',agg:'count'}}
function Builder({d,rows,onAdd}:{d:Dataset;rows:Row[];onAdd:(s:ChartSpec)=>void}){
 const defaults=useMemo(()=>builderDefaults(d.profiles),[]);
 const [kind,setKind]=useState<ChartSpec['kind']>(defaults.kind),[x,setX]=useState(defaults.x),[y,setY]=useState(defaults.y),[agg,setAgg]=useState<Aggregation>(defaults.agg),[interacted,setInteracted]=useState(false),[preview,setPreview]=useState<ChartSpec|null>(null);
 const xp=d.profiles.find(p=>p.name===x),yp=d.profiles.find(p=>p.name===y),usesY=builderUsesY(kind),usesAggregation=builderUsesAggregation(kind);
 const invalid=chartBuilderError(kind,xp,usesY?yp:undefined);
 const changeKind=(next:ChartSpec['kind'])=>{const currentX=d.profiles.find(p=>p.name===x),suggestedX=currentX&&validBuilderX(next,currentX)?currentX:d.profiles.find(p=>validBuilderX(next,p)),nextX=suggestedX?.name||x;setKind(next);setInteracted(true);if(suggestedX&&suggestedX.name!==x)setX(suggestedX.name);if(next==='line'||next==='scatter'){const currentY=d.profiles.find(p=>p.name===y);if(currentY?.type!=='numeric'||currentY.name===nextX)setY(d.profiles.find(p=>p.type==='numeric'&&p.name!==nextX)?.name||'')}if(next==='line'&&(agg==='count'||agg==='percentage')){const numeric=d.profiles.find(p=>p.type==='numeric'&&p.name!==nextX);setAgg(numericAggregation(numeric?.name||''))}};
 const aggregationOptions:Aggregation[]=kind==='line'?['sum','average','median','minimum','maximum']:['count','sum','average','median','minimum','maximum'];
 const spec=():ChartSpec=>({id:`custom-${Date.now()}`,title:kind==='scatter'?`${x} vs ${y}`:`${agg==='count'?'Records':y} by ${x}`,subtitle:`Custom ${kind} chart`,kind,x,y:usesY&&y?y:undefined,aggregation:usesAggregation?agg:undefined});
 const apply=()=>{setInteracted(true);if(!invalid)setPreview(spec())};
 return <section className="builder"><div className="section-title"><div><div className="eyebrow">Shape the story</div><h2>Build your own chart</h2></div><p>Choose fields and an aggregation. MarketLens will validate the combination before it renders.</p></div><div className="builder-grid"><label>Chart type<select value={kind} onChange={e=>changeKind(e.target.value as ChartSpec['kind'])}>{['bar','horizontal','line','donut','scatter','histogram'].map(option=><option key={option}>{option}</option>)}</select></label><label>X-axis<select value={x} onChange={e=>{setX(e.target.value);setInteracted(true)}}>{d.profiles.filter(p=>p.type!=='text').map(p=><option key={p.name} disabled={!validBuilderX(kind,p)||(usesY&&p.name===y)}>{p.name}</option>)}</select></label>{usesY&&<label>Y-axis<select value={y} onChange={e=>{setY(e.target.value);if(!e.target.value)setAgg('count');setInteracted(true)}}><option value="" disabled={kind==='line'||kind==='scatter'}>None</option>{d.profiles.filter(p=>p.type==='numeric').map(p=><option key={p.name} disabled={p.name===x}>{p.name}</option>)}</select></label>}{usesAggregation&&<label>Aggregation<select value={agg} onChange={e=>{setAgg(e.target.value as Aggregation);setInteracted(true)}}>{aggregationOptions.map(option=><option key={option} disabled={!y&&option!=='count'}>{option}</option>)}</select></label>}<button className="primary" disabled={!!invalid} aria-describedby={invalid&&interacted?'builder-validation':undefined} onClick={apply}>Apply</button></div>{invalid&&interacted&&<p id="builder-validation" role="alert" className="validation">{invalid}</p>}{preview&&<div className="builder-preview"><ChartCard rows={rows} spec={preview}/><button className="secondary" onClick={()=>onAdd(preview)}>+ Add to dashboard</button></div>}</section>
}
function DataGrid({rows,columns}:{rows:Row[];columns:string[]}){const [q,setQ]=useState('');const [page,setPage]=useState(0);const [sort,setSort]=useState('');const filtered=rows.filter(r=>!q||Object.values(r).some(v=>String(v).toLowerCase().includes(q.toLowerCase())));const sorted=sort?[...filtered].sort((a,b)=>String(a[sort]??'').localeCompare(String(b[sort]??''),undefined,{numeric:true})):filtered;const shown=sorted.slice(page*20,page*20+20);return <section className="data-section"><div className="section-title"><div><div className="eyebrow">Explore the records</div><h2>Filtered data</h2></div><button className="secondary" onClick={()=>downloadCsv(filtered,'marketlens-filtered.csv')}>Export CSV</button></div><div className="table-tools"><input aria-label="Search data rows" placeholder="Search rows…" value={q} onChange={e=>{setQ(e.target.value);setPage(0)}}/><span>{fmt(filtered.length)} rows</span></div><div className="table-wrap"><table><thead><tr>{columns.map(c=><th key={c}><button onClick={()=>setSort(c)}>{c}{sort===c?' ↑':''}</button></th>)}</tr></thead><tbody>{shown.map((r,i)=><tr key={i}>{columns.map(c=><td key={c}>{String(r[c]??'')}</td>)}</tr>)}</tbody></table></div><div className="pager"><button disabled={!page} onClick={()=>setPage(page-1)}>Previous</button><span>Page {page+1} of {Math.max(1,Math.ceil(filtered.length/20))}</span><button disabled={(page+1)*20>=filtered.length} onClick={()=>setPage(page+1)}>Next</button></div></section>}
export default function App(){const [d,setD]=useState<Dataset|null>(null);const [filters,setFilters]=useState<FilterState>({});const [custom,setCustom]=useState<ChartSpec[]>([]);if(!d)return <Upload onLoad={setD}/>;const rows=applyFilters(d.rows,filters);const charts=[...suggestCharts(d.profiles),...custom];const clean=(action:'duplicates'|'trim')=>{let r=d.rows;if(action==='duplicates')r=Array.from(new Map(r.map(x=>[JSON.stringify(x),x])).values());else r=r.map(x=>Object.fromEntries(Object.entries(x).map(([k,v])=>[k,typeof v==='string'?v.trim():v])));setD({...d,rows:r,profiles:profileRows(r)})};return <><Header onReset={()=>{setD(null);setFilters({});setCustom([])}}/><main className="dashboard"><Summary d={d} rows={rows}/><Filters d={d} value={filters} onChange={setFilters}/><section className="clean"><span><b>Optional cleaning</b> Changes are never applied silently.</span><button onClick={()=>clean('duplicates')}>Remove duplicates</button><button onClick={()=>clean('trim')}>Trim whitespace</button><button onClick={()=>setD(makeDataset(d.name,d.originalRows))}>Reset data</button></section><section className="charts"><div className="section-title"><div><div className="eyebrow">Automatic exploration</div><h2>Your data, in focus</h2></div><p>{charts.length} charts selected from the fields that actually exist.</p></div><div className="chart-grid">{charts.map(s=><ChartCard key={s.id} rows={rows} spec={s} onRemove={s.id.startsWith('custom')?()=>setCustom(custom.filter(x=>x.id!==s.id)):undefined}/>)}</div></section><section className="observations"><div className="eyebrow">Evidence, carefully stated</div><h2>Key observations</h2><div>{insights(rows,d.profiles).map((x,i)=><article key={x}><span>0{i+1}</span><p>{x}</p></article>)}</div><small>These are descriptive associations from the filtered dataset. They do not establish causation.</small></section><Builder d={d} rows={rows} onAdd={s=>setCustom([...custom,{...s,id:`custom-${custom.length}`}])}/><Profile d={d} setD={setD}/><details className="details-card"><summary><span><b>Data preview</b><small>First 20 filtered records</small></span><b>⌄</b></summary><PreviewTable rows={rows} columns={d.profiles.map(p=>p.name)}/></details><DataGrid rows={rows} columns={d.profiles.map(p=>p.name)}/></main><footer><span>MarketLens by Marceline Yu</span><nav aria-label="Portfolio links"><a href="https://github.com/Marcelineyu" target="_blank" rel="noopener noreferrer">GitHub</a><a href="https://github.com/Marcelineyu/marketlens" target="_blank" rel="noopener noreferrer">Repository</a><a href="https://www.linkedin.com/in/marcelineyu/" target="_blank" rel="noopener noreferrer">LinkedIn</a></nav></footer></>}
